# Generated by Django 5.2.4 on 2025-08-12 16:59

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5, validators=[portfolio.validators.is_valid_ticker])),
                ('name', models.CharField()),
                ('date_public', models.DateField()),
                ('exchange', models.CharField(choices=[('nyse', 'New York Stock Exchange'), ('s_p_500', 'S & P 500'), ('shanghai', 'Shanghai Stock Exchange'), ('japan', 'Japan Exchange Group'), ('london_innit', 'London Stock Exchange')])),
                ('sector', models.CharField(choices=[('tech', 'Technology'), ('health', 'Health'), ('finance', 'Finance'), ('data', 'Data and Information'), ('food_service', 'Food Services'), ('other', 'Miscellaneous')], default='other', max_length=20)),
            ],
        ),
    ]
