# Generated by Django 5.2.4 on 2025-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(choices=[('nyse', 'New York Stock Exchange'), ('s_p_500', 'S & P 500'), ('shanghai', 'Shanghai Stock Exchange'), ('japan', 'Japan Exchange Group'), ('london_innit', 'London Stock Exchange')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
